## API Description Composer [/composer]
Reverse the parsing process--compose an API description format.

### Compose [POST]

#### Input Media Types

##### API Elements

API Elements is supported, you can send an [API Elements API
Category](http://api-elements.readthedocs.io/en/latest/element-definitions/#category-base-api-element)
to the composer using the `application/vnd.refract+json` content type. You may
also send an [API Elements Parse
Result](http://api-elements.readthedocs.io/en/latest/element-definitions/#parse-result-elements)
as `application/vnd.refract.parse-result+json`.

```
application/vnd.refract+json
application/vnd.refract.parse-result+json
```

#### Output Media Types

##### API Blueprint

```
text/vnd.apiblueprint
```

API Blueprint as defined in its [specification](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md).

+ Relation: compose

+ Request Compose API Blueprint from API Elements API (application/vnd.refract+json)

        :[](fixtures/apib/normal.refract.json)

+ Response 200 (text/vnd.apiblueprint)

        :[](fixtures/apib/composer.apib)

+ Request Compose API Blueprint from API Elements Parse Result (application/vnd.refract.parse-result+json)

        :[](fixtures/apib/normal.refract.parse-result.json)

+ Response 200 (text/vnd.apiblueprint)

        :[](fixtures/apib/composer.apib)

+ Request Compose API Blueprint from API Elements 1.0 Parse Result (application/vnd.refract.parse-result+json; version=1.0)

        :[](fixtures/apib/normal.refract.parse-result.1.0.json)

+ Response 200 (text/vnd.apiblueprint)

        :[](fixtures/apib/composer.apib)

+ Request Compose API Blueprint from API Elements 0.6 Parse Result (application/vnd.refract.parse-result+json; version=0.6)

        :[](fixtures/apib/normal.refract.parse-result.json)

+ Response 200 (text/vnd.apiblueprint)

        :[](fixtures/apib/composer.apib)

+ Request Unknown Refract Version (application/vnd.refract.parse-result+json; version=2.0)

        {}

+ Response 415 (application/vnd.error+json)
    + Attributes
        + statusCode: 415 (number)
        + message: ``Unsupported Refract Serialisation version `2.0`. Supported: 0.6, 1.0.``
        + name: Rest Error

+ Request Unknown Content Type (application/vnd.apiblueprint.ast+json)

        {}

+ Response 415 (application/vnd.error+json)
    + Attributes
        + statusCode: 415 (number)
        + message: ``Unsupported Content-Type `application/vnd.apiblueprint.ast+json`. Supported: application/vnd.refract+json, application/vnd.refract.parse-result+json. API Blueprint AST is no longer supported.``
        + name: Rest Error
